spring.application.name=RemoteTrack

# Server port (for Render deployment)
server.port=${PORT:8080}
server.address=0.0.0.0

# Datasource (Supabase PostgreSQL)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres.tuxwzcsvxszfnonibmor}
spring.datasource.password=${DB_PASSWORD:pankaj@123PS}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://tuxwzcsvxszfnonibmor.supabase.co/auth/v1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://tuxwzcsvxszfnonibmor.supabase.co/auth/v1/.well-known/jwks.json